---
Comment: |
  Please Note: Due to recent changes to Docker, the postinstall
  script will only run for the current user. More info here
  https://dazwallace.wordpress.com/2022/12/02/changes-to-docker-desktop-for-mac/
Description: Downloads the latest versions of Docker (arm and intel) and creates a package.
Identifier: com.github.smithjw-actions.pkg.Docker
ParentRecipe: com.github.smithjw-actions.download.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker

Process:
  - Processor: PkgRootCreator
    Arguments:
      pkgroot: '%RECIPE_CACHE_DIR%/Universal'
      pkgdirs:
        pkgroot: '0775'
        scripts: '0775'

  - Processor: PkgRootCreator
    Arguments:
      pkgdirs:
        arm64/Applications: '0755'
        x86_64/Applications: '0755'
      pkgroot: '%RECIPE_CACHE_DIR%/payloads'

  - Processor: Copier
    Arguments:
      source_path: '%RECIPE_CACHE_DIR%/downloads/Docker-arm64.dmg/Docker.app'
      destination_path: '%RECIPE_CACHE_DIR%/payloads/arm64/Applications/Docker.app'

  - Processor: PlistReader
    Arguments:
      info_path: '%RECIPE_CACHE_DIR%/payloads/arm64/Applications/Docker.app/Contents/Info.plist'
      plist_keys:
        CFBundleShortVersionString: version
        CFBundleIdentifier: bundleid
        CFBundleName: app_name

  - Processor: PkgCreator
    Arguments:
      force_pkg_build: true
      pkg_request:
        chown:
          - path: Applications
            user: root
            group: wheel
        id: '%bundleid%'
        options: purge_ds_store
        pkgdir: '%RECIPE_CACHE_DIR%/Universal/scripts'
        pkgname: 'Docker-arm64-%version%'
        pkgroot: '%RECIPE_CACHE_DIR%/payloads/arm64'
        version: '%version%'

  - Processor: Copier
    Arguments:
      source_path: '%RECIPE_CACHE_DIR%/downloads/Docker-x86_64.dmg/Docker.app'
      destination_path: '%RECIPE_CACHE_DIR%/payloads/x86_64/Applications/Docker.app'

  - Processor: PlistReader
    Arguments:
      info_path: '%RECIPE_CACHE_DIR%/payloads/x86_64/Applications/Docker.app/Contents/Info.plist'
      plist_keys:
        CFBundleShortVersionString: version
        CFBundleIdentifier: bundleid
        CFBundleName: app_name

  - Processor: PkgCreator
    Arguments:
      force_pkg_build: true
      pkg_request:
        chown:
          - path: Applications
            user: root
            group: wheel
        id: '%bundleid%'
        options: purge_ds_store
        pkgdir: '%RECIPE_CACHE_DIR%/Universal/scripts'
        pkgname: 'Docker-x86_64-%version%'
        pkgroot: '%RECIPE_CACHE_DIR%/payloads/x86_64'
        version: '%version%'

  - Processor: FileCreator
    Arguments:
      file_path: '%RECIPE_CACHE_DIR%/Universal/scripts/preinstall'
      file_mode: '0755'
      file_content: |
        #!/bin/bash

        # arm64_package="Docker-arm64-%version%.pkg"
        arm64_dmg="Docker-arm64-%version%.dmg"
        # x86_64_package="Docker-x86_64-%version%.pkg"
        x86_64_dmg="Docker-x86_64-%version%.dmg"

        if [[ $( /usr/bin/arch ) = arm64* ]]; then
          /usr/sbin/installer -pkg "$arm64_package" -target "$3"
          hdiutil attach "$arm64_dmg" -nobrowse
        else
          /usr/sbin/installer -pkg "$x86_64_package" -target "$3"
          hdiutil attach "$x86_64_dmg" -nobrowse
        fi

        exit 0

  - Processor: FileCreator
    Arguments:
      file_path: '%RECIPE_CACHE_DIR%/Universal/scripts/postinstall'
      file_mode: '0755'
      file_content: |
        #!/bin/bash
        # https://forums.docker.com/t/feature-request-cli-tool-for-automated-installation/18334/4
        # https://github.com/autopkg/chilcote-recipes/blob/master/Docker/Docker.munki.recipe
        # https://github.com/docker/for-mac/issues/2359

        declare -r docker_bundle_dir=/Applications/Docker.app/Contents
        declare -r privtools=/Library/PrivilegedHelperTools
        declare -r usr_local_bin=/usr/local/bin

        [[ ! -d ${usr_local_bin} ]] && /bin/mkdir -p ${usr_local_bin} ; /bin/chmod 1755 ${usr_local_bin}

        for tool in docker docker-compose docker-diagnose docker-machine notary; do
          /bin/ln -sf ${docker_bundle_dir}/Resources/bin/${tool} /usr/local/bin
        done

        [[ ! -d ${privtools} ]] && /bin/mkdir -p ${privtools} ; /bin/chmod 1755 ${privtools}

        # unload com.docker.vmnetd if present
        if [[ -e /Library/LaunchDaemons/com.docker.vmnetd.plist ]] ; then
          /bin/launchctl unload /Library/LaunchDaemons/com.docker.vmnetd.plist
        fi

        /bin/echo "Installing Docker privileged components..."

        logged_in_user=$( scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }' )
        "/Applications/Docker.app/Contents/MacOS/install" --accept-license --user "${logged_in_user}"

        exit 0

  - Processor: PkgCreator
    Arguments:
      pkg_request:
        id: '%bundleid%'
        options: purge_ds_store
        pkgdir: '%RECIPE_CACHE_DIR%'
        pkgname: '%NAME%_Universal-%version%'
        pkgroot: '%RECIPE_CACHE_DIR%/Universal/pkgroot'
        scripts: '%RECIPE_CACHE_DIR%/Universal/scripts'
        version: '%version%'

  - Processor: com.github.smithjw.processors/FriendlyPathDeleter
    Arguments:
      fail_deleter_silently: true
      path_list:
        - '%RECIPE_CACHE_DIR%/Universal'
        - '%RECIPE_CACHE_DIR%/payloads'
