---
Description: Downloads the latest versions of Docker (Defaults to Apple Silicon)
Identifier: com.github.smithjw-actions.download.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker
  ARCHITECTURE: arm64
  DOWNLOAD_TYPE: arm64
  DOWNLOAD_MISSING_FILE:
  BYPASS_STOP_PROCESSING_IF_DOWNLOAD_UNCHANGED:

Process:
  - Processor: URLTextSearcher
    Arguments:
      re_pattern: '((\w+):\/\/(\S*)(%DOWNLOAD_TYPE%)(\S*)(dmg)(?=\?))'
      result_output_var_name: match
      url: 'https://www.docker.com/get-started'

  - Processor: com.github.jgstew.SharedProcessors/URLDownloaderPython
    Arguments:
      filename: 'Docker-%ARCHITECTURE%.dmg'
      download_dir: '%RECIPE_CACHE_DIR%/downloads'
      url: '%match%'
      download_missing_file: false

  - Processor: URLTextSearcher
    Arguments:
      re_pattern: '((\w+):\/\/(\S*)(amd64)(\S*)(dmg)(?=\?))'
      result_output_var_name: match
      url: 'https://www.docker.com/get-started'

  - Processor: com.github.jgstew.SharedProcessors/URLDownloaderPython
    Arguments:
      filename: 'Docker-x86_64.dmg'
      download_dir: '%RECIPE_CACHE_DIR%/downloads'
      url: '%match%'
      download_missing_file: '%DOWNLOAD_MISSING_FILE%'

  - Processor: EndOfCheckPhase
  - Processor: com.github.jgstew.SharedProcessors/StopProcessingIfDownloadUnchanged
    Arguments:
      bypass_stop_processing_if: '%BYPASS_STOP_PROCESSING_IF_DOWNLOAD_UNCHANGED%'

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%RECIPE_CACHE_DIR%/downloads/Docker-arm64.dmg/Docker.app'
      deep_verification: true
      strict_verification: true
      requirement: >-
        anchor apple generic and identifier "com.docker.docker" and
        (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or
        certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and
        certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and
        certificate leaf[subject.OU] = "9BNSXJN65R")

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%RECIPE_CACHE_DIR%/downloads/Docker-x86_64.dmg/Docker.app'
      deep_verification: true
      strict_verification: true
      requirement: >-
        anchor apple generic and identifier "com.docker.docker" and
        (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or
        certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and
        certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and
        certificate leaf[subject.OU] = "9BNSXJN65R")
